package guidelines.statemachine;

public enum GuideStates {
    CONFIG, CONFIG_AVAILABLE, INSERT_NAME, LAUNCH_STATE, HOME_ADDR, GET_DEST_NAME,
    GET_HOME_ADDR,
    GET_DEST_ADDR, HELP, HELP_DEST, HELP_HOME, TRANSIT, USE_GPS_OR_NOT, YES, HOME_ADDR_NAME, NO, SELECT_NEARBY_STATION,
    SAY_DEST_ADDR_AGAIN
}
